<?php

  $tours = array(
    "1" => array(
      "hotel" => "Club Tropical 4*",
      "anounce" => "1.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/4743",
      "region" => "Аланья",
      "price" => "31 680",
    ),
    "2" => array(
      "hotel" => "Grand Pearl Beach Resort & SPA 5*",
      "anounce" => "2.jpg",
      "link" => "http://ntk-intourist.kz/catalog.aspx?hotel_id=18011",
      "region" => "Сиде",
      "price" => "38 511",
    ),
    "3" => array(
      "hotel" => "Crystal Family Resort & Spa 5*",
      "anounce" => "3.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/4755",
      "region" => "Белек",
      "price" => "45 870",
    ),
    "4" => array(
      "hotel" => "Crystal Paraiso Verde Resort 5*",
      "anounce" => "4.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/8354",
      "region" => "Белек",
      "price" => "42 042",
    ),
    "5" => array(
      "hotel" => "Crystal Admiral Resort Suites & SPA 5*",
      "anounce" => "5.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/4786",
      "region" => "Сиде",
      "price" => "42 042",
    ),
    "6" => array(
      "hotel" => "Crystal Flora Beach Resort 5*",
      "anounce" => "6.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/10031",
      "region" => "Кемер",
      "price" => "47 751",
    ),
    "7" => array(
      "hotel" => "Crystal Deluxe Resort 5*",
      "anounce" => "7.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/4768",
      "region" => "Кемер",
      "price" => "47 751",
    ),
    "8" => array(
      "hotel" => "Elite Life 4*",
      "anounce" => "8.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/10331",
      "region" => "Кемер",
      "price" => "26 895",
    ),
    "9" => array(
      "hotel" => "Justiniano Club Alanya 4*",
      "anounce" => "9.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/4735",
      "region" => "Аланья",
      "price" => "37 851",
    ),
    "10" => array(
      "hotel" => "Justiniano Club Park Conti 5*",
      "anounce" => "10.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/745",
      "region" => "Аланья",
      "price" => "35 442",
    ),
    "11" => array(
      "hotel" => "Meryan 5*",
      "anounce" => "11.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/2217",
      "region" => "Аланья",
      "price" => "37 026",
    ),
    "12" => array(
      "hotel" => "Pemar Beach Resort 5*",
      "anounce" => "12.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/9869",
      "region" => "Сиде",
      "price" => "38 214",
    ),
    "13" => array(
      "hotel" => "Poseidon SOHO Beach Club HV-1",
      "anounce" => "13.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/14668",
      "region" => "Белек",
      "price" => "38 973",
    ),
    "14" => array(
      "hotel" => "Rixos Hotel Premium 5*",
      "anounce" => "14.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/1022",
      "region" => "Белек",
      "price" => "92 400",
    ),
    "15" => array(
      "hotel" => "Sea Bird Beach Hotel 3*",
      "anounce" => "15.jpg",
      "link" => "http://ntk-intourist.kz/catalog.aspx?hotel_id=6859",
      "region" => "Аланья",
      "price" => "24 849",
    ),
    "16" => array(
      "hotel" => "Sentido Zeynep Golf&SPA 5*",
      "anounce" => "16.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/14703",
      "region" => "Белек",
      "price" => "58 047",
    ),
    "17" => array(
      "hotel" => "Sunset Beach 5*",
      "anounce" => "17.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/9967",
      "region" => "Аланья",
      "price" => "32 703",
    ),
    "18" => array(
      "hotel" => "Intourist Maxim Resort 5*",
      "anounce" => "18.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/1198",
      "region" => "Кемер",
      "price" => "41 448",
    ),
    "19" => array(
      "hotel" => "Turan Prince Residence 5*",
      "anounce" => "19.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/893",
      "region" => "Сиде",
      "price" => "44 748",
    ),
    "20" => array(
      "hotel" => "Club Hotel Turan Prince World HV-1",
      "anounce" => "20.jpg",
      "link" => "http://msk.ntk-intourist.ru/countries/turkey/hotel/135",
      "region" => "Сиде",
      "price" => "52 173",
    ),
  );

?>